/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Xeeshan
 */
public class Addmition_page extends javax.swing.JPanel {
Connection conn= null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Addmition_page
     */
    public Addmition_page() {
        initComponents();
         conn = Connect_database.connecerDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addmition_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        f_name_txt = new javax.swing.JTextField();
        show_cmd = new javax.swing.JButton();
        name_txt = new javax.swing.JTextField();
        birth_txt = new javax.swing.JTextField();
        Gr_no = new javax.swing.JTextField();
        Phone_no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fee_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add_cmd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        class_txt = new javax.swing.JComboBox<>();

        jLabel8.setText("Phone No");

        show_cmd.setText("Show Record");
        show_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_cmdActionPerformed(evt);
            }
        });

        birth_txt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                birth_txtAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel6.setText("Fee");

        jLabel1.setText("G.R.NO");

        jLabel2.setText("Name");

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        add_cmd.setText("Addmition ");
        add_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cmdActionPerformed(evt);
            }
        });

        jLabel4.setText("Date Of Birth");

        jLabel3.setText("S/O");

        jLabel7.setText("Class");

        class_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "9th", "10th", "1st year", "2nd year" }));
        class_txt.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                class_txtPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout addmition_panelLayout = new javax.swing.GroupLayout(addmition_panel);
        addmition_panel.setLayout(addmition_panelLayout);
        addmition_panelLayout.setHorizontalGroup(
            addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmition_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmition_panelLayout.createSequentialGroup()
                                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Gr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(addmition_panelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(fee_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addmition_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(class_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address_txt)
                            .addGroup(addmition_panelLayout.createSequentialGroup()
                                .addComponent(birth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(add_cmd)
                        .addGap(30, 30, 30)
                        .addComponent(show_cmd)
                        .addContainerGap(269, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        addmition_panelLayout.setVerticalGroup(
            addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmition_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_txt)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(class_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_name_txt)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fee_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addmition_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(addmition_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_cmd)
                    .addComponent(show_cmd))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(addmition_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addmition_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void show_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_cmdActionPerformed
        Show_Record_1 a= new Show_Record_1();
        a.setVisible(true);
    }//GEN-LAST:event_show_cmdActionPerformed

    private void birth_txtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_birth_txtAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_txtAncestorAdded

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void add_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cmdActionPerformed

        String temp =class_txt.getSelectedItem().toString();
        if (temp=="Select Class"){
            JOptionPane.showMessageDialog(null, "Please First Select Class");
        }else{
            try{
                String sql= "Insert into addmition (G_R_Number,Class,Name,F_name,Fee,Phone_number,Address,Date_of_birth) values(?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1, Gr_no.getText());
                pst.setString(2, temp);
                pst.setString(3, name_txt.getText());
                pst.setString(4, f_name_txt.getText());
                pst.setString(5, fee_txt.getText());
                pst.setString(6, Phone_no.getText());
                pst.setString(7, address_txt.getText());
                pst.setString(8, birth_txt.getText());
                pst.execute();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_add_cmdActionPerformed

    private void class_txtPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_class_txtPopupMenuWillBecomeInvisible
        String combo=(String) class_txt.getSelectedItem();
        if(combo=="Select Class"){
            Gr_no.setText(" ");
        }
        if(combo=="9th"){
            Gr_no.setText("A");
        }
        if(combo=="10th"){
            Gr_no.setText("B");
        }
        if(combo=="1st year"){
            Gr_no.setText("C");
        }
        if(combo=="2nd year"){
            Gr_no.setText("D");
        }
    }//GEN-LAST:event_class_txtPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Gr_no;
    private javax.swing.JTextField Phone_no;
    private javax.swing.JButton add_cmd;
    private javax.swing.JPanel addmition_panel;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField birth_txt;
    private javax.swing.JComboBox<String> class_txt;
    private javax.swing.JTextField f_name_txt;
    private javax.swing.JTextField fee_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton show_cmd;
    // End of variables declaration//GEN-END:variables
}
