/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.HeadlessException;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
/**
 *
 * @author Xeeshan
 */
public class Show_Record_1 extends javax.swing.JFrame  {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Show_Record
     */
    public Show_Record_1() {
        initComponents();
        conn= Connect_database.connecerDb();
        Update_table();
    }
    
     private void Update_table(){
       try{
           String sql="Select * from addmition  where Class='9th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_one.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }finally{
          closedatabse();
            }
       
       
       
         try{
           String sql="Select * from addmition  where Class='10th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_two.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            } 
             finally{
          closedatabse();
            } 
         
         
         
         
         try{
           String sql="Select * from addmition  where Class='1st year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_three.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }finally{
         closedatabse();
            }
         
         
         
         
         try{
           String sql="Select * from addmition  where Class='2nd year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_four.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }finally{
          closedatabse();
            } 
         
         try{
           String sql="Select * from addmition  where Class='B.S.C'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_five.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }finally{
          closedatabse();
            }
       
       
       
         try{
           String sql="Select * from addmition  where Class='B.Com'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_six.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            } 
             finally{
          closedatabse();
            } 
       
    }
     
     public void closedatabse(){
        
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_one = new javax.swing.JTable();
        search_table_one = new javax.swing.JTextField();
        combo_one_txt = new javax.swing.JComboBox<>();
        Delete_table_one = new javax.swing.JButton();
        Print_table_one = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_two = new javax.swing.JTable();
        Print_table_two = new javax.swing.JButton();
        Delete_table_two = new javax.swing.JButton();
        search_table_two = new javax.swing.JTextField();
        combo_two_txt = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_three = new javax.swing.JTable();
        Print_table_three = new javax.swing.JButton();
        Delete_table_three = new javax.swing.JButton();
        search_table_three = new javax.swing.JTextField();
        combo_three_txt = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_four = new javax.swing.JTable();
        Print_table_four = new javax.swing.JButton();
        Delete_table_four = new javax.swing.JButton();
        search_table_four = new javax.swing.JTextField();
        combo_four_txt = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_five = new javax.swing.JTable();
        search_table_five = new javax.swing.JTextField();
        combo_five_txt = new javax.swing.JComboBox<>();
        Delete_table_five = new javax.swing.JButton();
        Print_table_five = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_six = new javax.swing.JTable();
        search_table_six = new javax.swing.JTextField();
        combo_six_txt = new javax.swing.JComboBox<>();
        Delete_table_six = new javax.swing.JButton();
        Print_table_six = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Information");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setOpaque(false);

        table_one.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_one);

        search_table_one.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_oneKeyReleased(evt);
            }
        });

        combo_one_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        Delete_table_one.setText("Delete");
        Delete_table_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_oneActionPerformed(evt);
            }
        });

        Print_table_one.setText("Print");
        Print_table_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_oneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_one_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_one, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730)
                .addComponent(Delete_table_one)
                .addGap(18, 18, 18)
                .addComponent(Print_table_one)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_one)
                    .addComponent(Delete_table_one)
                    .addComponent(search_table_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_one_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Class 9th", jPanel4);

        jPanel1.setOpaque(false);

        table_two.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_two);

        Print_table_two.setText("Print");
        Print_table_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_twoActionPerformed(evt);
            }
        });

        Delete_table_two.setText("Delete");
        Delete_table_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_twoActionPerformed(evt);
            }
        });

        search_table_two.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_twoKeyReleased(evt);
            }
        });

        combo_two_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_two_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_two, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_two)
                .addGap(18, 18, 18)
                .addComponent(Print_table_two)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_two)
                    .addComponent(Delete_table_two)
                    .addComponent(combo_two_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_table_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Class 10th", jPanel1);

        jPanel2.setOpaque(false);

        table_three.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_three);

        Print_table_three.setText("Print");
        Print_table_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_threeActionPerformed(evt);
            }
        });

        Delete_table_three.setText("Delete");
        Delete_table_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_threeActionPerformed(evt);
            }
        });

        search_table_three.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_threeKeyReleased(evt);
            }
        });

        combo_three_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_three_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_three, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730)
                .addComponent(Delete_table_three)
                .addGap(18, 18, 18)
                .addComponent(Print_table_three)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_three)
                    .addComponent(Delete_table_three)
                    .addComponent(search_table_three, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_three_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("1st Year", jPanel2);

        jPanel3.setOpaque(false);

        table_four.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_four);

        Print_table_four.setText("Print");
        Print_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_fourActionPerformed(evt);
            }
        });

        Delete_table_four.setText("Delete");
        Delete_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_fourActionPerformed(evt);
            }
        });

        search_table_four.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_fourKeyReleased(evt);
            }
        });

        combo_four_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_four_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_four, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730)
                .addComponent(Delete_table_four)
                .addGap(18, 18, 18)
                .addComponent(Print_table_four)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four)
                    .addComponent(Delete_table_four)
                    .addComponent(search_table_four, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_four_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2nd Year", jPanel3);

        jPanel5.setOpaque(false);

        table_five.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(table_five);

        search_table_five.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_fiveKeyReleased(evt);
            }
        });

        combo_five_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        Delete_table_five.setText("Delete");
        Delete_table_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_fiveActionPerformed(evt);
            }
        });

        Print_table_five.setText("Print");
        Print_table_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_fiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_five_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_five, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730)
                .addComponent(Delete_table_five)
                .addGap(18, 18, 18)
                .addComponent(Print_table_five)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_five)
                    .addComponent(Delete_table_five)
                    .addComponent(search_table_five, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_five_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("B.S.C", jPanel5);

        jPanel6.setOpaque(false);

        table_six.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(table_six);

        search_table_six.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_table_sixKeyReleased(evt);
            }
        });

        combo_six_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "G_R no", "Name" }));

        Delete_table_six.setText("Delete");
        Delete_table_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_sixActionPerformed(evt);
            }
        });

        Print_table_six.setText("Print");
        Print_table_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_sixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_six_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_table_six, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730)
                .addComponent(Delete_table_six)
                .addGap(18, 18, 18)
                .addComponent(Print_table_six)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_six)
                    .addComponent(Delete_table_six)
                    .addComponent(search_table_six, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_six_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("B.Com", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1120, 540));
        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background_Form.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jMenu1.setText("File");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Addmition");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("LogOut");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Update");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("view");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Show Record");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Fee Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
     
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void Print_table_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_twoActionPerformed
   MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_two.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_twoActionPerformed

    private void Print_table_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_threeActionPerformed
        MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_three.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_threeActionPerformed

    private void Print_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_fourActionPerformed
       MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_four.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_fourActionPerformed

    private void Delete_table_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_twoActionPerformed
        
         try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_two.getSelectedRow();
           String Tabel_click=(table_two.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
          closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_twoActionPerformed

    private void Delete_table_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_threeActionPerformed
           try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_three.getSelectedRow();
           String Tabel_click=(table_three.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
         closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_threeActionPerformed

    private void Delete_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_fourActionPerformed
        try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_four.getSelectedRow();
           String Tabel_click=(table_four.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
          closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_fourActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        Addnition_page add=new Addnition_page();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Login_page log =new Login_page();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Update_page u= new Update_page();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Show_Record_1 s= new Show_Record_1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        fee_info f= new fee_info();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void search_table_threeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_threeKeyReleased
       String search= search_table_three.getText();    
           String combo= combo_three_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_three.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_three.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
         }
    }//GEN-LAST:event_search_table_threeKeyReleased

    private void search_table_fourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_fourKeyReleased
      String search= search_table_four.getText();    
           String combo= combo_four_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_four.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_four.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
         }
    }//GEN-LAST:event_search_table_fourKeyReleased

    private void search_table_twoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_twoKeyReleased
           String search= search_table_two.getText();    
           String combo= combo_two_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_two.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_two.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
         }
    }//GEN-LAST:event_search_table_twoKeyReleased

    private void search_table_oneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_oneKeyReleased
       
        String search= search_table_one.getText();
           String combo= combo_one_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_one.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_one.setModel(DbUtils.resultSetToTableModel(rs));  
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
             
         }
        
    }//GEN-LAST:event_search_table_oneKeyReleased

    private void Delete_table_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_oneActionPerformed
       try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_one.getSelectedRow();
           String Tabel_click=(table_one.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
          closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_oneActionPerformed

    private void Print_table_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_oneActionPerformed
         MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_one.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_oneActionPerformed

    private void search_table_fiveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_fiveKeyReleased
        String search= search_table_five.getText();    
           String combo= combo_five_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_five.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_five.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
         }
    }//GEN-LAST:event_search_table_fiveKeyReleased

    private void Delete_table_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_fiveActionPerformed
         try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_five.getSelectedRow();
           String Tabel_click=(table_five.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
          closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_fiveActionPerformed

    private void Print_table_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_fiveActionPerformed
         MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_five.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_fiveActionPerformed

    private void search_table_sixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_table_sixKeyReleased
        String search= search_table_six.getText();    
           String combo= combo_six_txt.getSelectedItem().toString();
        if("Search".equals(combo)){
               JOptionPane.showMessageDialog(null, "please first select");
           }
         if (combo=="G_R no"){ 
         try{    
               String sql="Select * from addmition where G_R_Number='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_six.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
    } 
         else if(combo=="Name"){
              try{    
               String sql="Select * from addmition where Name='"+search+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_six.setModel(DbUtils.resultSetToTableModel(rs));   
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
         closedatabse();
            }   
         }
    }//GEN-LAST:event_search_table_sixKeyReleased

    private void Delete_table_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_sixActionPerformed
         try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_six.getSelectedRow();
           String Tabel_click=(table_six.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);   
    }finally{
          closedatabse();
            }
         Update_table();
    }//GEN-LAST:event_Delete_table_sixActionPerformed

    private void Print_table_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_sixActionPerformed
         MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_six.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_sixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_Record_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_Record_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_Record_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_Record_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Show_Record_1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_table_five;
    private javax.swing.JButton Delete_table_four;
    private javax.swing.JButton Delete_table_one;
    private javax.swing.JButton Delete_table_six;
    private javax.swing.JButton Delete_table_three;
    private javax.swing.JButton Delete_table_two;
    private javax.swing.JButton Print_table_five;
    private javax.swing.JButton Print_table_four;
    private javax.swing.JButton Print_table_one;
    private javax.swing.JButton Print_table_six;
    private javax.swing.JButton Print_table_three;
    private javax.swing.JButton Print_table_two;
    private javax.swing.JComboBox<String> combo_five_txt;
    private javax.swing.JComboBox<String> combo_four_txt;
    private javax.swing.JComboBox<String> combo_one_txt;
    private javax.swing.JComboBox<String> combo_six_txt;
    private javax.swing.JComboBox<String> combo_three_txt;
    private javax.swing.JComboBox<String> combo_two_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField search_table_five;
    private javax.swing.JTextField search_table_four;
    private javax.swing.JTextField search_table_one;
    private javax.swing.JTextField search_table_six;
    private javax.swing.JTextField search_table_three;
    private javax.swing.JTextField search_table_two;
    private javax.swing.JTable table_five;
    private javax.swing.JTable table_four;
    private javax.swing.JTable table_one;
    private javax.swing.JTable table_six;
    private javax.swing.JTable table_three;
    private javax.swing.JTable table_two;
    // End of variables declaration//GEN-END:variables
}
