/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
/**
 *
 * @author Xeeshan
 */
public class Show_Record_1 extends javax.swing.JFrame  {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Show_Record
     */
    public Show_Record_1() {
        initComponents();
        conn= Connect_database.connecerDb();
        Update_table();
    }
    
     private void Update_table(){
       try{
           String sql="Select * from addmition  where Class='9th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           show_table.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
         try{
           String sql="Select * from addmition  where Class='10th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_two.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       } 
        try{
           String sql="Select * from addmition  where Class='1st year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_three.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       } 
         try{
           String sql="Select * from addmition  where Class='2nd year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_four.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       } 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_two = new javax.swing.JTable();
        Print_table_two = new javax.swing.JButton();
        Delete_table_two = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_three = new javax.swing.JTable();
        Print_table_three = new javax.swing.JButton();
        Delete_table_three = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_four = new javax.swing.JTable();
        Print_table_four = new javax.swing.JButton();
        Delete_table_three1 = new javax.swing.JButton();
        Delete_table_four = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        table_two.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_two);

        Print_table_two.setText("Print");
        Print_table_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_twoActionPerformed(evt);
            }
        });

        Delete_table_two.setText("Delete");
        Delete_table_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_twoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_two)
                .addGap(18, 18, 18)
                .addComponent(Print_table_two)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_two)
                    .addComponent(Delete_table_two))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Class 10th", jPanel1);

        table_three.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_three);

        Print_table_three.setText("Print");
        Print_table_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_threeActionPerformed(evt);
            }
        });

        Delete_table_three.setText("Delete");
        Delete_table_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_threeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_three)
                .addGap(18, 18, 18)
                .addComponent(Print_table_three)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_three)
                    .addComponent(Delete_table_three))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1st Year", jPanel2);

        table_four.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_four);

        Print_table_four.setText("Print");
        Print_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_fourActionPerformed(evt);
            }
        });

        Delete_table_three1.setText("Delete");
        Delete_table_three1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_three1ActionPerformed(evt);
            }
        });

        Delete_table_four.setText("Delete");
        Delete_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_fourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_four)
                .addGap(18, 18, 18)
                .addComponent(Print_table_four)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(421, 421, 421)
                    .addComponent(Delete_table_three1)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four)
                    .addComponent(Delete_table_four))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(Delete_table_three1)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("2nd Year", jPanel3);

        show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(show_table);

        jTabbedPane1.addTab("Class 9th", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
     
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void Print_table_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_twoActionPerformed
   MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_two.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_twoActionPerformed

    private void Print_table_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_threeActionPerformed
        MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_three.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_threeActionPerformed

    private void Print_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_fourActionPerformed
       MessageFormat header =new MessageFormat("Report Print");
     MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
          table_four.print(JTable.PrintMode.NORMAL,header,footer);
      }catch(java.awt.print.PrinterException e){
          
          System.err.format("connot Print %s%n", e.getMessage());
      }
    }//GEN-LAST:event_Print_table_fourActionPerformed

    private void Delete_table_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_twoActionPerformed
        
         try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_two.getSelectedRow();
           String Tabel_click=(table_two.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);   
    }
         Update_table();
    }//GEN-LAST:event_Delete_table_twoActionPerformed

    private void Delete_table_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_threeActionPerformed
           try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_three.getSelectedRow();
           String Tabel_click=(table_three.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);   
    }
         Update_table();
    }//GEN-LAST:event_Delete_table_threeActionPerformed

    private void Delete_table_three1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_three1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_table_three1ActionPerformed

    private void Delete_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_fourActionPerformed
        try{
             String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_four.getSelectedRow();
           String Tabel_click=(table_four.getModel().getValueAt(row, 0).toString()); 
           pst=conn.prepareStatement(sql);
           pst.setString(1,Tabel_click );
           pst.execute();
           JOptionPane.showMessageDialog(null," Deleted" );
       }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);   
    }
         Update_table();
    }//GEN-LAST:event_Delete_table_fourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_Record_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_table_four;
    private javax.swing.JButton Delete_table_three;
    private javax.swing.JButton Delete_table_three1;
    private javax.swing.JButton Delete_table_two;
    private javax.swing.JButton Print_table_four;
    private javax.swing.JButton Print_table_three;
    private javax.swing.JButton Print_table_two;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable show_table;
    private javax.swing.JTable table_four;
    private javax.swing.JTable table_three;
    private javax.swing.JTable table_two;
    // End of variables declaration//GEN-END:variables
}
