/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
/**
 *
 * @author Xeeshan
 */
public class Update_page extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Update_page
     */
    public Update_page() {
        initComponents();
        conn= Connect_database.connecerDb();
        Update_table();
    }
     
   private void Update_table(){
       try{
           String sql="Select * from addmition  where Class='9th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_one_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
              }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
       
       
       
       
         try{
           String sql="Select * from addmition  where Class='10th'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_two_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            } finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
         
         
         
        try{
           String sql="Select * from addmition  where Class='1st year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_three_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
        
        
        
        
         try{
           String sql="Select * from addmition  where Class='2nd year'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_four_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            } 
         
         try{
           String sql="Select * from addmition  where Class='B.S.C'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_five_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
              }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
         
         
         
         try{
           String sql="Select * from addmition  where Class='B.Com'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           table_six_info.setModel(DbUtils.resultSetToTableModel(rs));
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
              }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        show_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fee_txt = new javax.swing.JTextField();
        Update_cmd = new javax.swing.JButton();
        Gr_no = new javax.swing.JTextField();
        class_txt = new javax.swing.JComboBox<>();
        Phone_no = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        f_name_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        Clear_cmd = new javax.swing.JButton();
        jTabbedPane14 = new javax.swing.JTabbedPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        table_one_info = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        Print_table_two9 = new javax.swing.JButton();
        Delete_table_two9 = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        table_two_info = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        table_three_info = new javax.swing.JTable();
        Print_table_three4 = new javax.swing.JButton();
        Delete_table_three4 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        table_four_info = new javax.swing.JTable();
        Print_table_four = new javax.swing.JButton();
        Delete_table_four = new javax.swing.JButton();
        Delete_table_four1 = new javax.swing.JButton();
        Print_table_four1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        table_five_info = new javax.swing.JTable();
        Delete_table_four3 = new javax.swing.JButton();
        Print_table_four3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        table_six_info = new javax.swing.JTable();
        Delete_table_four2 = new javax.swing.JButton();
        Print_table_four2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(show_table);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Addmition Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        address_txt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phone No");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Class");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fee");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");

        fee_txt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        Update_cmd.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        Update_cmd.setText("Update");
        Update_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_cmdActionPerformed(evt);
            }
        });

        Gr_no.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        class_txt.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        class_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "9th", "10th", "1st year", "2nd year", "B.S.C", "B.Com" }));
        class_txt.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                class_txtPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        Phone_no.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S/O");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G.R.NO");

        f_name_txt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        name_txt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        Clear_cmd.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Clear_cmd.setText("Clear");
        Clear_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_cmdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Gr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(fee_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(class_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(address_txt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Clear_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Update_cmd)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_txt)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(class_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_name_txt)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fee_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Update_cmd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Clear_cmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 560, -1));

        jTabbedPane14.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jTabbedPane14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane14StateChanged(evt);
            }
        });
        jTabbedPane14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane14MouseClicked(evt);
            }
        });

        table_one_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_one_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_one_infoMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(table_one_info);

        jTabbedPane14.addTab("Class 9th", jScrollPane18);

        jPanel15.setOpaque(false);

        Print_table_two9.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Print_table_two9.setText("Print");
        Print_table_two9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_two9ActionPerformed(evt);
            }
        });

        Delete_table_two9.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Delete_table_two9.setText("Delete");
        Delete_table_two9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_two9ActionPerformed(evt);
            }
        });

        table_two_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_two_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_two_infoMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(table_two_info);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(Delete_table_two9)
                .addGap(18, 18, 18)
                .addComponent(Print_table_two9)
                .addContainerGap())
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_two9)
                    .addComponent(Delete_table_two9))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jTabbedPane14.addTab("Class 10th", jPanel15);

        jPanel16.setOpaque(false);

        table_three_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_three_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_three_infoMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(table_three_info);

        Print_table_three4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Print_table_three4.setText("Print");
        Print_table_three4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_three4ActionPerformed(evt);
            }
        });

        Delete_table_three4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Delete_table_three4.setText("Delete");
        Delete_table_three4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_three4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(Delete_table_three4)
                .addGap(18, 18, 18)
                .addComponent(Print_table_three4)
                .addContainerGap())
            .addComponent(jScrollPane16)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_three4)
                    .addComponent(Delete_table_three4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane14.addTab("1st Year", jPanel16);

        jPanel17.setOpaque(false);

        table_four_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_four_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_four_infoMouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(table_four_info);

        Print_table_four.setText("Print");
        Print_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_fourActionPerformed(evt);
            }
        });

        Delete_table_four.setText("Delete");
        Delete_table_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_fourActionPerformed(evt);
            }
        });

        Delete_table_four1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Delete_table_four1.setText("Delete");
        Delete_table_four1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_four1ActionPerformed(evt);
            }
        });

        Print_table_four1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Print_table_four1.setText("Print");
        Print_table_four1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_four1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(Delete_table_four)
                        .addGap(18, 18, 18)
                        .addComponent(Print_table_four))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(Delete_table_four1)
                        .addGap(18, 18, 18)
                        .addComponent(Print_table_four1)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four1)
                    .addComponent(Delete_table_four1))
                .addGap(54, 54, 54)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four)
                    .addComponent(Delete_table_four))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane14.addTab("2nd Year", jPanel17);

        jPanel2.setOpaque(false);

        table_five_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_five_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_five_infoMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(table_five_info);

        Delete_table_four3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Delete_table_four3.setText("Delete");
        Delete_table_four3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_four3ActionPerformed(evt);
            }
        });

        Print_table_four3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Print_table_four3.setText("Print");
        Print_table_four3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_four3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_four3)
                .addGap(18, 18, 18)
                .addComponent(Print_table_four3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four3)
                    .addComponent(Delete_table_four3))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jTabbedPane14.addTab("B.S.C", jPanel2);

        jPanel3.setOpaque(false);

        table_six_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_six_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_six_infoMouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(table_six_info);

        Delete_table_four2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Delete_table_four2.setText("Delete");
        Delete_table_four2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_table_four2ActionPerformed(evt);
            }
        });

        Print_table_four2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Print_table_four2.setText("Print");
        Print_table_four2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_table_four2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_table_four2)
                .addGap(18, 18, 18)
                .addComponent(Print_table_four2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_table_four2)
                    .addComponent(Delete_table_four2))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jTabbedPane14.addTab("B.Com", jPanel3);

        getContentPane().add(jTabbedPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 640, 559));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background_Form.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        jMenu1.setText("File");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Addmition");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("LogOut");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Update");
        jMenuItem5.setEnabled(false);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("view");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Show Record");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Fee Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void Update_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_cmdActionPerformed
          String temp =class_txt.getSelectedItem().toString();
        try{
            String value1=Gr_no.getText();
            String value2= temp;
            String value3=name_txt.getText();
            String value4=f_name_txt.getText();
            String value5=fee_txt.getText();
            String value6=Phone_no.getText();
            String value7=address_txt.getText();
           String sql= "update  addmition  set G_R_Number='"+value1+"',Class='"+value2+"',Name='"+value3+"',F_name='"+value4+"',Fee='"+value5+"',Phone_Number='"+value6+"',Address='"+value7+"' where  G_R_Number='"+value1+"'";
           pst=conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null," updated" );
       }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);   
    }
        finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
        Update_table();
                           
    }//GEN-LAST:event_Update_cmdActionPerformed

    private void class_txtPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_class_txtPopupMenuWillBecomeInvisible
        String combo=(String) class_txt.getSelectedItem();
        if(combo=="Select Class"){
            Gr_no.setText(" ");
        }
        if(combo=="9th"){
            Gr_no.setText("A");
        }
        if(combo=="10th"){
            Gr_no.setText("B");
        }
        if(combo=="1st year"){
            Gr_no.setText("C");
        }
        if(combo=="2nd year"){
            Gr_no.setText("D");
        }
    }//GEN-LAST:event_class_txtPopupMenuWillBecomeInvisible

    private void Print_table_two9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_two9ActionPerformed
        MessageFormat header =new MessageFormat("Report Print");
        MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
            table_two_info.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){

            System.err.format("connot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_Print_table_two9ActionPerformed

    private void Delete_table_two9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_two9ActionPerformed

        try{
            String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_two_info.getSelectedRow();
            String Tabel_click=(table_two_info.getModel().getValueAt(row, 0).toString());
            pst=conn.prepareStatement(sql);
            pst.setString(1,Tabel_click );
            pst.execute();
            JOptionPane.showMessageDialog(null," Deleted" );
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_Delete_table_two9ActionPerformed

    private void Print_table_three4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_three4ActionPerformed
        MessageFormat header =new MessageFormat("Report Print");
        MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
            table_three_info.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){

            System.err.format("connot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_Print_table_three4ActionPerformed

    private void Delete_table_three4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_three4ActionPerformed
        try{
            String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_three_info.getSelectedRow();
            String Tabel_click=(table_three_info.getModel().getValueAt(row, 0).toString());
            pst=conn.prepareStatement(sql);
            pst.setString(1,Tabel_click );
            pst.execute();
            JOptionPane.showMessageDialog(null," Deleted" );
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_Delete_table_three4ActionPerformed

    private void Print_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_fourActionPerformed
        MessageFormat header =new MessageFormat("Report Print");
        MessageFormat footer =new MessageFormat("page{0,number,integer}");
        try{
            table_four_info.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){

            System.err.format("connot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_Print_table_fourActionPerformed

    private void Delete_table_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_fourActionPerformed
        try{
            String sql= "delete  from  addmition where G_R_number=? ";
            int row =table_four_info.getSelectedRow();
            String Tabel_click=(table_four_info.getModel().getValueAt(row, 0).toString());
            pst=conn.prepareStatement(sql);
            pst.setString(1,Tabel_click );
            pst.execute();
            JOptionPane.showMessageDialog(null," Deleted" );
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_Delete_table_fourActionPerformed

    private void jTabbedPane14StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane14StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane14StateChanged

    private void jTabbedPane14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane14MouseClicked

    }//GEN-LAST:event_jTabbedPane14MouseClicked

    private void Delete_table_four1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_four1ActionPerformed
        
    }//GEN-LAST:event_Delete_table_four1ActionPerformed

    private void Print_table_four1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_four1ActionPerformed
       
    }//GEN-LAST:event_Print_table_four1ActionPerformed

    private void table_two_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_two_infoMouseClicked
        try{
           int row =table_two_info.getSelectedRow();
           String Tabel_click=(table_two_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
        
    }//GEN-LAST:event_table_two_infoMouseClicked

    private void table_three_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_three_infoMouseClicked
         try{
           int row =table_three_info.getSelectedRow();
           String Tabel_click=(table_three_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
    }//GEN-LAST:event_table_three_infoMouseClicked

    private void table_four_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_four_infoMouseClicked
         try{
           int row =table_four_info.getSelectedRow();
           String Tabel_click=(table_four_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
    }//GEN-LAST:event_table_four_infoMouseClicked

    private void table_one_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_one_infoMouseClicked
       try{
           int row =table_one_info.getSelectedRow();
           String Tabel_click=(table_one_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
    }//GEN-LAST:event_table_one_infoMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        Addnition_page add=new Addnition_page();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Login_page log =new Login_page();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Update_page u= new Update_page();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Show_Record_1 s= new Show_Record_1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        fee_info f= new fee_info();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Clear_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_cmdActionPerformed
    
               Gr_no.setText("");
               class_txt.setSelectedItem("Select Class");
               name_txt.setText("");
               f_name_txt.setText("");
               fee_txt.setText("");
               Phone_no.setText("");
               address_txt.setText("");
    }//GEN-LAST:event_Clear_cmdActionPerformed

    private void table_six_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_six_infoMouseClicked
         try{
           int row =table_six_info.getSelectedRow();
           String Tabel_click=(table_six_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
    }//GEN-LAST:event_table_six_infoMouseClicked

    private void Delete_table_four2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_four2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_table_four2ActionPerformed

    private void Print_table_four2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_four2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Print_table_four2ActionPerformed

    private void table_five_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_five_infoMouseClicked
          try{
           int row =table_five_info.getSelectedRow();
           String Tabel_click=(table_five_info.getModel().getValueAt(row, 0).toString());
              String sql="select * from addmition where G_R_Number='"+Tabel_click+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           if(rs.next()){
               String add1=rs.getString("G_R_Number");
               Gr_no.setText(add1);
               String add2=rs.getString("Class");
               class_txt.setSelectedItem(add2);
               String add3=rs.getString("Name");
               name_txt.setText(add3);
               String add4=rs.getString("F_name");
               f_name_txt.setText(add4);
               String add5=rs.getString("Fee");
               fee_txt.setText(add5);
               String add6=rs.getString("Phone_number");
               Phone_no.setText(add6);
               String add7=rs.getString("Address");
               address_txt.setText(add7);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }finally{
          try{
              rs.close();
              pst.close();
             }catch(Exception e){
                           }
            }
    }//GEN-LAST:event_table_five_infoMouseClicked

    private void Delete_table_four3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_table_four3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_table_four3ActionPerformed

    private void Print_table_four3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_table_four3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Print_table_four3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_cmd;
    private javax.swing.JButton Delete_table_four;
    private javax.swing.JButton Delete_table_four1;
    private javax.swing.JButton Delete_table_four2;
    private javax.swing.JButton Delete_table_four3;
    private javax.swing.JButton Delete_table_three4;
    private javax.swing.JButton Delete_table_two9;
    private javax.swing.JTextField Gr_no;
    private javax.swing.JTextField Phone_no;
    private javax.swing.JButton Print_table_four;
    private javax.swing.JButton Print_table_four1;
    private javax.swing.JButton Print_table_four2;
    private javax.swing.JButton Print_table_four3;
    private javax.swing.JButton Print_table_three4;
    private javax.swing.JButton Print_table_two9;
    private javax.swing.JButton Update_cmd;
    private javax.swing.JTextField address_txt;
    private javax.swing.JComboBox<String> class_txt;
    private javax.swing.JTextField f_name_txt;
    private javax.swing.JTextField fee_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane14;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTable show_table;
    private javax.swing.JTable table_five_info;
    private javax.swing.JTable table_four_info;
    private javax.swing.JTable table_one_info;
    private javax.swing.JTable table_six_info;
    private javax.swing.JTable table_three_info;
    private javax.swing.JTable table_two_info;
    // End of variables declaration//GEN-END:variables
}
